### PR TITLE
Major Refactoring of Decode.py

### PR DESCRIPTION
**Pull request by Arkajit-Datta**
**Major changes and updates in this refactoring**

1. Changed "email" and "mobile" statuses to boolean from yes/no (strings). Boolean values make it easy to be parsed at a later stage Also, reduces subsequent lines of code in both Mobile Registered and Email Registered methods.
2. The __init__ method was too loaded with various variable initializations and processing. The code inside the function has been broken down into numerous private methods making the whole code more readable.
3. The logic to assign values to email and mobile statuses has been updated, it now checks for conditions such as 3/1 and 3/2 to assign True, else both the statuses are defaulted to False. This again reduces subsequent lines of redundant code.

### CODE REVIEW

**Comment by Arkajit-Datta** [comment]
Hey Tanmoy, 
I have added some refactoring changes, which makes the code more readable, please review the changes once. 

Thanks and Regards

**Comment by Tanmoy741127** [comment]
Sorry ! I have not got time today. Tomorrow morning i will check and
approve if no changes required.
ᐧ

**Comment by Arkajit-Datta** [comment]
Sure, Tanmoy!

Thanks and Regards

**Comment by Arkajit-Datta** [comment]
Hey Tanmoy, 
Any issues in the PR? 

Thanks and Regards

**Comment by Arkajit-Datta** [comment]
Hey Tanmoy, 
Can this be taken as hacktober accepted?

**Comment by Tanmoy741127** [comment]
Sure wait a bit

**Comment by Arkajit-Datta** [comment]
Thanks tanmoy, i have found a few more issues. Will raise them shortly. 

Regards

**Comment by Tanmoy741127** [comment]
> Thanks tanmoy, i have found a few more issues. Will raise them shortly.
> 
> Regards

Sure

**Pull request merged**
