### PR TITLE
Bug Fixes in MobileNoRegistered and EmailRegistered Methods

### PR DESCRIPTION
**Pull request by Arkajit-Datta**
This PR is corresponding to the latest issue being raised.

### CODE REVIEW

**Comment by Tanmoy741127** [comment]
Is it backward compaitable ? Because old aadhaar cards has this status no

**Comment by Arkajit-Datta** [comment]
So, essentially this change must not affect the Old Aadhaar Card flow. As we have a separate class for that, all together

**Comment by Tanmoy741127** [comment]
Ok , I will go through the docs once, and upon confirming will merge that sure.

**Comment by Arkajit-Datta** [comment]
Also, extracting the fields from Old Aadhaar QRs we don't get these fields, hence I don't think so we will face any issues.

**Comment by Arkajit-Datta** [comment]
> Ok , I will go through the docs once, and upon confirming will merge that sure.

Thanks!

**Comment by Arkajit-Datta** [comment]
I will probably try to refactor the code a bit, we can possibly reduce a few redundant lines

**Comment by Tanmoy741127** [comment]
Sure

**Comment by Arkajit-Datta** [comment]
Will raise another PR with refactoring changes, looking forward to a quick merge :)

**Comment by Arkajit-Datta** [comment]
Hey Tanmoy! 
Is there a problem with the PR? 

Thanks and Regards
Arkajit Datta

**Comment by Tanmoy741127** [comment]
> Hey Tanmoy! Is there a problem with the PR?
> 
> Thanks and Regards Arkajit Datta

No Issue !
Thanks

**Pull request merged**
